# yaml-language-server: $schema=https://json.schemastore.org/backstage-template.json
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Template Options
      type: object
      properties:
        placeholder:
          type: string
          title: Text Placeholder
          description: Temporary field to keep the schema valid

  steps:
    - id: create-file
      name: Create-file
      action: my:custom:action
      input:
        filename: example.txt
        contents: This is my custom action!